language: python
dist: xenial
python:
- 2.7
- 3.6
- 3.7
- pypy
- pypy3
install: pip install tox-travis
script: tox
after_success: 
cache:
  pip: true
notifications:
  webhooks:
    secure: Zawtb5E43G7Uiu4hhxPyfEmRz4sPN06r1RTXE5Q22YTvRCLNxE+AhKINab2WZwqCDp+fF0hCCZcLzt0h1FC+E3MkLcawmECcdlA478yVwQIfe9JZ42r2OQ6h9W9o/NSmUudl1L9yeZ7supaJwlkTHYjkcf0rpQDrMsvfwBlS482kOl0NEU3iyPjRFt5tnxYFsBmB4P0KydMzgi+1Mkl+rivW8V5li6S4LytgIXVl7TRPFWmV0yay6SdTJ7nwuQDkpeQ8GlHCLmtTk29FJ5Lyaqj+zkTI1197LFr0xmQi1Z6/iKAogVtdoSrYwsAUfaygTwGhfq3HEkEGdLYuqnfa+jTg+gETnOKUqn7ta3Af4RjjNPbHCLvxgIijwZPksy0sCAQNRYkpnoymRoE51hfc/xMkULpBaUMV15UkQGYMVsRvyXKwY/QHMZd9VmdFfmTDsMNMtPh/6y24sX+ys+xgl0DDw1J3RvQVAwbp6u4hMmJ8MBBCDWFgFcCr65jaL7wyr/aqgWYuIg/IIY64Lw0v4spo0dJUqRGRDKksQPquX0gvrNoiu7PCQJ9nnnu2BHV+tCGBbO4a3q3yUl394rEWm/v+oLKINXEAYvi5nakU1RRo6xDXWA8oguBXsq6/jcFpMUxoK0JCgKVtkzzmX9jQp84C80ov0KUlBFghdkMiHdM=
