# Generated with zope.meta (https://zopemeta.readthedocs.io/)
[project]
name = "gocept.testing"
version = "6.0.dev0"
description = "A collection of test helpers, additional assertions, and the like."
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Testing",
]
dynamic = ["readme"]
requires-python = ">=3.10"
authors = [
    {name = "minddistrict <mail at minddistrict dot com>",email = "mail@minddistrict.com"},
]
maintainers = [
    {name = "Plone Foundation and contributors",email = "zope-dev@zope.dev"},
]
keywords = ["testing", "unittest", "assertions"]

[project.urls]
Source = "https://github.com/minddistrict/gocept.testing"
Documentation = "https://github.com/minddistrict/gocept.testing/blob/main/README.rst"
Issues = "https://github.com/minddistrict/gocept.testing/issues"
Changelog = "https://raw.githubusercontent.com/minddistrict/gocept.testing/main/CHANGES.rst"

[tool.setuptools.dynamic]
readme = {file = ["README.rst", "CHANGES.rst"]}
