name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.9",   "py39"]
        - ["3.10",  "py310"]
        - ["3.11",  "py311"]
        - ["3.12",  "py312"]
        - ["3.13",  "py313"]
        - ["pypy-3.10", "pypy3"]
        - ["3.11",   "coverage"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.config[0] }}
        allow-prereleases: true
    - name: Pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
    - name: Coverage
      if: matrix.config[1] == 'coverage'
      run: |
        pip install coveralls coverage-python-version
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
